import TurndownService from 'turndown';
import type { RequestHandler } from '@sveltejs/kit';
import { sitemapConfig } from '$lib/sitemap-config';

const turndown = new TurndownService({
	headingStyle: 'atx',
	codeBlockStyle: 'fenced'
});

turndown.keep(['table']);

function extractTagContent(html: string, tag: string) {
	const match = html.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`, 'i'));
	return match ? match[1].trim() : '';
}

function extractMetaContent(html: string, name: string) {
	const match = html.match(
		new RegExp(`<meta[^>]+name=["']${name}["'][^>]*content=["']([^"']*)["'][^>]*>`, 'i')
	);
	return match ? match[1].trim() : '';
}

function extractMainHtml(html: string) {
	const mainMatch = html.match(/<main[^>]*>([\s\S]*?)<\/main>/i);
	if (mainMatch) return mainMatch[1];
	const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
	if (bodyMatch) return bodyMatch[1];
	return html;
}

function stripNonContent(html: string) {
	return html
		.replace(/<script[\s\S]*?<\/script>/gi, '')
		.replace(/<style[\s\S]*?<\/style>/gi, '')
		.replace(/<link[\s\S]*?>/gi, '')
		.replace(/<noscript[\s\S]*?<\/noscript>/gi, '');
}

function yamlString(value: string) {
	const sanitized = value.replace(/\r?\n/g, ' ').trim();
	return JSON.stringify(sanitized);
}

function toTitleFromPath(pathname: string) {
	if (pathname === '/') return 'Home';
	const segment = pathname.replace(/\/$/, '').split('/').pop() || 'Home';
	return segment
		.replace(/[-_]+/g, ' ')
		.replace(/\b\w/g, (char) => char.toUpperCase());
}

export async function handleIndexMarkdown({ url, fetch }: Parameters<RequestHandler>[0]) {
	const normalizedPath = url.pathname.replace(/\/index\.md$/, '') || '/';
	const htmlPath = normalizedPath === '/' ? '/' : normalizedPath.replace(/\/$/, '');
	const htmlUrl = new URL(htmlPath + url.search, url.origin);

	const htmlRequest = new Request(htmlUrl.toString(), {
		headers: { accept: 'text/html' }
	});
	let htmlResponse: Response;
	try {
		// Use a real HTTP fetch to ensure SSR runs for pages.
		htmlResponse = await globalThis.fetch(htmlRequest);
	} catch {
		htmlResponse = await fetch(htmlRequest);
	}

	if (!htmlResponse.ok) {
		return new Response('Not found', { status: htmlResponse.status });
	}

	const html = await htmlResponse.text();
	const title = extractTagContent(html, 'title') || toTitleFromPath(normalizedPath);
	const description = extractMetaContent(html, 'description');
	const lastUpdated = new Date().toISOString();

	const contentHtml = stripNonContent(extractMainHtml(html));
	const markdownBody = turndown.turndown(contentHtml).trim();

	const canonicalPath = normalizedPath === '/' ? '/' : `${normalizedPath.replace(/\/$/, '')}/`;
	const frontmatter = [
		'---',
		`title: ${yamlString(title)}`,
		`description: ${yamlString(description)}`,
		`lastUpdated: ${lastUpdated}`,
		'builtWith: byob.studio',
		'llmsTxt: autogenerated by byob.studio',
		'chatbotDeprioritize: false',
		'source_url:',
		`  html: ${sitemapConfig.baseUrl}${canonicalPath}`,
		`  md: ${sitemapConfig.baseUrl}${canonicalPath}index.md`,
		'---',
		''
	].join('\n');

	return new Response(`${frontmatter}${markdownBody}\n`, {
		headers: {
			'content-type': 'text/markdown; charset=utf-8'
		}
	});
}
